basic world file
AerialRobotics-IITK/ariitk_fpv_racing pull request #1
Opened 2020-03-20 08:18 UTC by isro01

This has the .world file and the model.sdf file in the iros2016_track folder

2020-03-20 08:36 UTC, rohanblueboybaijal approved these changes

2020-03-20 08:37 UTC, ashwin2802 requested changes
rename the basic_world to worlds. We will put this in one of the packages later. i think iros2016_track should be moved to a directory specifically containing external submodules (@gajena). don't move that for now.

2020-03-21 05:31 UTC, ashwin2802 approved these changes

2020-03-21 06:03 UTC, PenceMataria approved these changes

2020-03-21 06:14 UTC, PenceMataria reviewed
Can have a proper repo with all our gazebo customization/creations/borrowings which can be linked. Might be useful for later stages too.

2020-03-21 09:11 UTC, gajena commented on simulator/package.xml
> +  <!-- The *depend tags are used to specify dependencies -->
remove these comments.

2020-03-21 09:15 UTC, gajena commented on simulator/worlds/blue_frames.world
> +<sdf version='1.6'>
name of the file must be intutive, like this is world file then name something like basic_arena ... something something

2020-03-21 10:09 UTC, merged

2020-03-21 10:10 UTC, ashwin2802 commented
great work!