Testing detection
AerialRobotics-IITK/ariitk_fpv_racing pull request #6
Opened 2020-03-27 14:36 UTC by isro01

Having issues with the detection(not satisfactory)...

2020-03-27 14:53 UTC, ashwin2802 commented on detector/include/detector/detector.hpp
> +    class Detector {
remove indentation

2020-03-27 14:53 UTC, ashwin2802 commented on detector/package.xml
> +  <!-- Example: -->
remove these comments

2020-03-27 14:54 UTC, ashwin2802 commented on detector/src/detector.cpp
> +
indentation

2020-03-27 14:56 UTC, ashwin2802 commented on detector/src/detector.cpp
> +    //     cv::waitKey(10);
remove these comments since you won't use this

2020-03-27 14:57 UTC, ashwin2802 commented on detector/src/detector.cpp
> +        hsv_min_ = cv::Scalar(h,s,v);
hsv_max_, not hsv_min_

2020-03-27 14:58 UTC, ashwin2802 commented on detector_msgs/package.xml
> +  <!-- Authors do not have to be maintainers, but could be -->
remove comments

2020-03-27 14:59 UTC, ashwin2802 commented on detector_ros/include/detector_ros/detector_ros.hpp
> +
indentation yeet

2020-03-27 14:59 UTC, ashwin2802 commented on detector_ros/package.xml
> +  <!-- <author email="jane.doe@example.com">Jane Doe</author> -->
comments yeet

2020-03-28 05:53 UTC, ashwin2802 commented on detector_ros/src/detector_ros.cpp
> +}
ending namespace comment

2020-03-28 05:54 UTC, ashwin2802 commented on detector/src/detector.cpp
> +}
ending namespace comment

2020-03-28 05:56 UTC, ashwin2802 requested changes
please try to make the whitespace after brackets and inside functions uniform everywhere. I'll try and test this code on my RotorS today.

2020-04-04 20:41 UTC, ashwin2802 commented on detector/package.xml
> +  <export>
remove this

2020-04-04 20:41 UTC, ashwin2802 commented on detector/package.xml
> +  <!-- Optional attribute type can be: website, bugtracker, or repository -->
remove this comment and stray empty lines

2020-04-04 20:42 UTC, ashwin2802 commented on detector/include/detector/detector.hpp
> +}   // namespace ariitk::detector
leave a blank line at EOF. please check in all files

2020-04-04 20:42 UTC, ashwin2802 commented on detector/src/detector.cpp
> +}
if it's empty, just define it in the header itself

2020-04-04 20:44 UTC, ashwin2802 commented on detector/src/detector.cpp
> +}
all these mini sized functions (except ```setCannyParams``` isn't mini), put them directly in the header. this will keep the cpp cleaner

2020-04-04 20:45 UTC, ashwin2802 commented on detector_msgs/package.xml
> +  <!-- Optional attribute type can be: website, bugtracker, or repository -->
remove all comments and boilerplate

2020-04-04 20:45 UTC, ashwin2802 commented on detector_ros/config/param.yaml
> +s_max: 255
if possible, add a short description of the params. have a look at the planning library param files.

2020-04-04 20:45 UTC, ashwin2802 commented on detector_ros/include/detector_ros/detector_ros.hpp
> +namespace ariitk::detector_ros{
space :)

2020-04-04 20:46 UTC, ashwin2802 commented on detector_ros/package.xml
> +  <!-- Optional attribute type can be: website, bugtracker, or repository -->
cleanup

2020-04-04 20:47 UTC, ashwin2802 commented on detector_ros/src/detector_ros.cpp
> +int h_min,s_min,v_min,h_max,s_max,v_max,canny_lower,canny_upper,min_contour_area,canny_ker;
don't define global variables, ever. put these inside init, and space them properly.

2020-04-04 20:47 UTC, ashwin2802 commented on detector_ros/src/detector_ros.cpp
> +    nh.getParam("h_max",h_max);nh.getParam("s_max",s_max);nh.getParam("v_max",v_max);
space these out a little

2020-04-04 20:48 UTC, ashwin2802 commented on detector_ros/src/detector_ros.cpp
> +    ros::NodeHandle nh_private("~");
also use private node handle to get the params, since you'll load the param file inside the node

2020-04-04 20:48 UTC, ashwin2802 commented on detector_ros/src/detector_ros.cpp
> +    nh.getParam("canny_lower",canny_lower);nh.getParam("canny_upper",canny_upper);nh.getParam("min_contour_area",min_contour_area);nh.getParam("canny_ker",canny_ker);
put these on separate lines

2020-04-04 20:49 UTC, ashwin2802 commented on simulator/launch/basic_track.launch
> +            <remap from="image_raw" to="camera_front/image_raw"/>
load your param file inside the detector_ros node.

2020-04-04 20:50 UTC, ashwin2802 commented on simulator/launch/basic_track.launch
> +          <arg name="model" value="$(find simulator)/models/urdf/mav_with_camera.gazebo" />
keep all the value tags in the same vertical column, this increases readability. you can look at the planning lib launch files for reference.

2020-04-04 20:51 UTC, ashwin2802 commented on simulator/launch/basic_track.launch
> +            <remap from="image_raw" to="camera_front/image_raw"/>
do these changes in your launch file

2020-04-04 20:52 UTC, ashwin2802 requested changes
good work, but just a little more finishing

2020-04-05 12:48 UTC, ashwin2802 approved these changes
good work!

2020-04-05 12:57 UTC, rohanblueboybaijal approved these changes

2020-04-05 12:59 UTC, merged

2020-04-06 06:45 UTC, PenceMataria commented
Great! Other things are working fine, except there is some kernel size error in canny due to which the node dies, please check that out and merge it back if it is sorted. 
PS. I dont think this should be system specific, didn't you guys faced this?

2020-04-07 03:46 UTC, amartyadash commented
> Great! Other things are working fine, except there is some kernel size error in canny due to which the node dies, please check that out and merge it back if it is sorted.
> PS. I dont think this should be system specific, didn't you guys faced this?

Yeah I faced this as well.